name: Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: threeal/cmake-action@main
      with:
        generator: Unix Makefiles
        source-dir: .
        build-dir: ./build
        options: CMAKE_BUILD_TYPE=Release
        build-args:  --config Release --target install
